### ISSUE TITLE
Shift tab back helper should be hidden if on first group

### ISSUE THREAD

**Issue by lucasoares** [charmbracelet/huh#194] opened 2024-04-19 02:47 UTC
**Describe the bug**
The helper `shift+tab back` should be hidden on the first group of a form because there is no group to back to.

**To Reproduce**

Create a form with a single group and execute it.

**Screenshots**

![image](https://github.com/charmbracelet/huh/assets/10624972/6dd9a4fd-98cc-47ee-b2fc-edf4b3ae3ec7)

**Comment by maaslalani** [comment] 2024-04-25 18:39
You're absolutely correct! Thank you so much for this issue!

**Comment by maaslalani** [comment] 2024-04-25 18:42
Hey! @lucasoares What version / commit of `huh?` are you on. I can reproduce with a simple example. Can you share the code that you're using:

<img width="496" alt="image" src="https://github.com/charmbracelet/huh/assets/42545625/c504efbb-1ad3-4cfd-8927-7251e875dd84">

**Comment by lucasoares** [comment] 2024-04-25 20:17
```
	github.com/charmbracelet/bubbles v0.18.0
	github.com/charmbracelet/bubbletea v0.25.0
	github.com/charmbracelet/huh v0.3.0
	github.com/charmbracelet/huh/spinner v0.0.0-20240321161533-278656239a9d
```

**Comment by lucasoares** [comment] 2024-05-09 22:09
The first time I execute the form:
![image](https://github.com/charmbracelet/huh/assets/10624972/23a45d13-b3fa-4ad7-85cf-439f1e7cf8ed)

Then if I move my selection the help text changes:
![image](https://github.com/charmbracelet/huh/assets/10624972/2daa83c9-4611-4352-a36d-f61084c0c272)

Also, if I press `tab` in the first option, it confirms the selection, but only `enter` should do it.

If I press any key when I'm in the first option, the help text changes too, and `tab` key will not confirm anymore. The following example I executed the form, pressed `x` and then tried to press `tab` 
![image](https://github.com/charmbracelet/huh/assets/10624972/5ffb5a6e-b18b-4b58-9d5f-5912e740e726)

**Comment by maaslalani** [comment] 2024-05-25 17:17
Hey, we fixed this on `main`! Will release soon.

The problem was setting the keymaps and that was fixed in https://github.com/charmbracelet/huh/commit/8c5d66193f2b83a5b6ff2443dec16964d7fe2bb7

**Closed by maaslalani** 2024-05-25 17:17 UTC
